/*
 * Fallback catalogue for Library Roguelike: 40 invented books in the same
 * shape as assets/data/library.json, used only when the real catalogue
 * cannot be fetched (for example when the page is opened from file://).
 * None of these books exist.
 */
window.LR_SAMPLE = [
  { id: 'X-X1-01', u: 'X', s: 'X1', p: 1, t: 'A Grammar of Forgotten Verbs', a: 'M. Ashdown', pub: 'Tolbooth', l: 'EN', ty: 'Language study', g: 'Language study & reference', st: 'OK', y: 1978, yr: '1978', d: 'A reference grammar of verbs that fell out of use before anyone wrote them down. Paradigms, exceptions, and a long chapter on the subjunctive of regret.' },
  { id: 'X-X1-02', u: 'X', s: 'X1', p: 2, t: 'Adequate Calculus, 5th ed.', a: 'R. Pell & T. Ng', pub: 'Broadstone', l: 'EN', ty: 'Textbook', g: 'Math, CS & engineering', st: 'OK', y: 1994, yr: '1994 (5th ed.)', d: 'Introductory calculus text for students who need it but do not want it. Limits, derivatives, integrals, and series, with answers to the odd-numbered exercises only.' },
  { id: 'X-X1-03', u: 'X', s: 'X1', p: 3, t: 'Ash and Ledger', a: 'Ione Petrakis', pub: 'Halfmoon', l: 'EN', ty: 'Fiction', g: 'Literature (English & European)', st: 'OK', y: 2011, yr: '2011', d: 'A novel about an accountant who inherits a ruined vineyard and the ledger that explains why it burned.' },
  { id: 'X-X1-04', u: 'X', s: 'X1', p: 4, t: 'The Bright Room', a: 'Cal Ferrer', pub: 'Halfmoon', l: 'EN', ty: 'Poetry', g: 'Literature (English & European)', st: 'OK', y: 2003, yr: '2003', d: 'Short lyric poems about hospitals, kitchens, and other rooms with too much light. Winner of a small prize.' },
  { id: 'X-X1-05', u: 'X', s: 'X1', p: 5, t: 'Chronicles of the Salt Road', a: 'Dagny Holm', pub: 'Meridian', l: 'EN', ty: 'History', g: 'History & biography', st: 'OK', y: 1962, yr: '1962', d: 'History of the overland salt trade from the Sahel to the Mediterranean, with maps of caravan routes and a chapter on the tax collectors who followed them.' },
  { id: 'X-X1-06', u: 'X', s: 'X1', p: 6, t: 'Companion to the Lesser Saints', a: '', pub: 'Ordo Press', l: 'EN/LA', ty: 'Religion', g: 'Religion & theology', st: 'OK', y: 1931, yr: '1931', d: 'Devotional companion listing feast days, prayers, and the improbable deeds of saints who never made the main calendar.' },
  { id: 'X-X1-07', u: 'X', s: 'X1', p: 7, t: 'Dust Season, vol. 3', a: 'Kei Morimoto', pub: 'Kodansha', l: 'JA', ty: 'Manga', g: 'Manga & comics', st: 'OK', y: 2016, yr: '2016', d: 'Third volume of a manga about a courier crossing a drought-stricken province with a letter no one wants delivered.' },
  { id: 'X-X2-01', u: 'X', s: 'X2', p: 1, t: 'Eight Ways to Look at a Wall', a: 'Helene Baptiste', pub: 'Palisade', l: 'EN', ty: 'Art', g: 'Art & visual culture', st: 'OK', y: 2008, yr: '2008', d: 'Large-format survey of mural painting from Pompeii to the present, with fold-out plates and an essay on plaster.' },
  { id: 'X-X2-02', u: 'X', s: 'X2', p: 2, t: 'Everything Is Negotiable Except This', a: 'Bram Tully', pub: 'Ascent', l: 'EN', ty: 'Self-help', g: 'Psychology, self-help & business', st: 'OK', y: 2019, yr: '2019', d: 'Business self-help book on negotiation, with worksheets, anecdotes about a shipping magnate, and one chapter the author admits contradicts the rest.' },
  { id: 'X-X2-03', u: 'X', s: 'X2', p: 3, t: 'Fever Charts', a: 'S. Okonkwo', pub: 'Halfmoon', l: 'EN', ty: 'Fiction', g: 'Literature (English & European)', st: 'OK', y: 1999, yr: '1999', d: 'Linked stories set in a night ward, each told by a different patient and ending at dawn.' },
  { id: 'X-X2-04', u: 'X', s: 'X2', p: 4, t: 'Foundations of Wireless Nothing', a: 'D. Larkin', pub: 'Broadstone', l: 'EN', ty: 'Technical', g: 'Math, CS & engineering', st: 'OK', y: 2005, yr: '2005', d: 'Engineering text on radio propagation, antennas, and the noise floor. Dense, well indexed, and heavier than it looks.' },
  { id: 'X-X2-05', u: 'X', s: 'X2', p: 5, t: 'The Gardener of Questions', a: 'Piotr Adamczyk', pub: 'Meridian', l: 'EN', ty: 'Philosophy', g: 'Philosophy & political theory', st: 'OK', y: 1987, yr: '1987', d: 'Essays on why answers are less useful than well-tended questions. Includes a long argument against argument.' },
  { id: 'X-X2-06', u: 'X', s: 'X2', p: 6, t: 'Glass Kanji', a: '', pub: 'Tuttle', l: 'EN/JA', ty: 'Language study', g: 'Language study & reference', st: 'OK', y: 2014, yr: '2014', d: 'Kanji workbook built around transparent overlays so the learner can trace strokes over printed characters.' },
  { id: 'X-X2-07', u: 'X', s: 'X2', p: 7, t: 'Hymns for a Cold Chapel', a: '', pub: 'Ordo Press', l: 'EN', ty: 'Hymnal', g: 'Religion & theology', st: 'OK', y: 1904, yr: '1904', d: 'Hymnal for small congregations without an organ. Melodies only, responsive readings, and the order of service for a winter funeral.' },
  { id: 'Y-Y1-01', u: 'Y', s: 'Y1', p: 1, t: 'Ink Wars', a: 'Tamsin Reed', pub: 'Palisade', l: 'EN', ty: 'History', g: 'History & biography', st: 'OK', y: 2012, yr: '2012', d: 'History of the rivalry between two Victorian printing houses, their libel suits, and the typeface each stole from the other.' },
  { id: 'Y-Y1-02', u: 'Y', s: 'Y1', p: 2, t: 'Introduction to Regret Theory', a: 'A. Whitlock', pub: 'Broadstone', l: 'EN', ty: 'Textbook', g: 'Math, CS & engineering', st: 'OK', y: 1990, yr: '1990', d: 'Decision theory textbook on choices made under the expectation of regret. Proofs, exercises, and a preface apologising for the title.' },
  { id: 'Y-Y1-03', u: 'Y', s: 'Y1', p: 3, t: 'The Journal of Implausible Results, vol. 12', a: '', pub: '', l: 'EN', ty: 'Magazine', g: 'Magazines & catalogues', st: 'OK', y: 2001, yr: '2001', d: 'Bound volume of a satirical science journal. Letters to the editor, one legitimate paper, and an index of retractions.' },
  { id: 'Y-Y1-04', u: 'Y', s: 'Y1', p: 4, t: 'Knot Theory for Sailors', a: 'E. Marsh', pub: 'Meridian', l: 'EN', ty: 'Science', g: 'Science', st: 'OK', y: 1975, yr: '1975', d: 'Popular mathematics book explaining knot invariants through actual knots, with rope diagrams and a plea to stop using the bowline as an example.' },
  { id: 'Y-Y1-05', u: 'Y', s: 'Y1', p: 5, t: 'Lantern Street, vol. 1', a: 'Aya Nishikawa', pub: 'Shueisha', l: 'JA', ty: 'Manga', g: 'Manga & comics', st: 'OK', y: 2020, yr: '2020', d: 'First volume of a slice-of-life manga about a street of lantern makers and the apprentice who keeps setting things on fire.' },
  { id: 'Y-Y1-06', u: 'Y', s: 'Y1', p: 6, t: 'Lantern Street, vol. 2', a: 'Aya Nishikawa', pub: 'Shueisha', l: 'JA', ty: 'Manga', g: 'Manga & comics', st: 'OK', y: 2020, yr: '2020', d: 'Second volume. The apprentice is promoted, against everyone’s advice.' },
  { id: 'Y-Y1-07', u: 'Y', s: 'Y1', p: 7, t: 'Manners for the Recently Dead', a: 'Ursula Fenn', pub: 'Halfmoon', l: 'EN', ty: 'Fiction', g: 'Literature (English & European)', st: 'OK', y: 2015, yr: '2015', d: 'Comic novel in which a ghost attends an etiquette course. Sequel announced but never published.' },
  { id: 'Y-Y2-01', u: 'Y', s: 'Y2', p: 1, t: 'Notes Toward a Theory of Corridors', a: 'J. Halloran', pub: 'Meridian', l: 'EN', ty: 'Philosophy', g: 'Society, culture & ideas', st: 'OK', y: 1996, yr: '1996', d: 'Cultural theory of hallways, waiting rooms, and other spaces built to be passed through rather than used.' },
  { id: 'Y-Y2-02', u: 'Y', s: 'Y2', p: 2, t: 'On Not Finishing', a: 'Cal Ferrer', pub: 'Halfmoon', l: 'EN', ty: 'Essays', g: 'Writing, film & literary craft', st: 'OK', y: 2010, yr: '2010', d: 'Essays on abandoned drafts, from unfinished symphonies to the last chapter the author claims not to have written.' },
  { id: 'Y-Y2-03', u: 'Y', s: 'Y2', p: 3, t: 'Pale Kingdoms', a: 'Dagny Holm', pub: 'Meridian', l: 'EN', ty: 'History', g: 'History & biography', st: 'OK', y: 1958, yr: '1958', d: 'Survey of northern European kingdoms between the Viking age and the Hanseatic League. Old, thorough, and unforgiving of the reader’s memory.' },
  { id: 'Y-Y2-04', u: 'Y', s: 'Y2', p: 4, t: 'Pharmacology Made Slightly Easier, 3rd ed.', a: 'L. Brandt', pub: 'Broadstone', l: 'EN', ty: 'Nursing & medical', g: 'Nursing & medical', st: 'OK', y: 2009, yr: '2009 (3rd ed.)', d: 'Nursing pharmacology review with drug tables, dosage calculations, and mnemonics that are hard to unlearn.' },
  { id: 'Y-Y2-05', u: 'Y', s: 'Y2', p: 5, t: 'The Quiet Ones', a: 'Ione Petrakis', pub: 'Halfmoon', l: 'EN', ty: 'Fiction', g: 'Literature (English & European)', st: 'OK', y: 2018, yr: '2018', d: 'Novel about three siblings who inherit a lighthouse and refuse, separately, to speak of it.' },
  { id: 'Y-Y2-06', u: 'Y', s: 'Y2', p: 6, t: 'Rain Sonnets', a: 'Mireille Auger', pub: 'Palisade', l: 'EN', ty: 'Poetry', g: 'Literature (English & European)', st: 'OK', y: 1971, yr: '1971', d: 'Fifty-two sonnets, one for each week of a wet year. The final couplets are famously unpredictable.' },
  { id: 'Y-Y2-07', u: 'Y', s: 'Y2', p: 7, t: '未来の後に', a: '黒田砂', pub: '新潮社', l: 'JA', ty: 'Fiction', g: 'Japanese literature', st: 'OK', y: 2004, yr: '2004', d: 'Japanese novel told in reverse, beginning with a wedding and ending with a train missed twenty years earlier.' },
  { id: 'Z-Z1-01', u: 'Z', s: 'Z1', p: 1, t: 'Sacred Geometry of the Kitchen Table', a: 'R. Voss', pub: 'Ordo Press', l: 'EN', ty: 'Occult', g: 'Occult & folklore', st: 'OK', y: 1983, yr: '1983', d: 'Folk-occult manual for arranging household objects into protective patterns. Diagrams, salt, and a warning about spoons.' },
  { id: 'Z-Z1-02', u: 'Z', s: 'Z1', p: 2, t: 'SAT Vocabulary Siege', a: '', pub: 'Ascent', l: 'EN', ty: 'Test prep', g: 'Test prep & study guides', st: 'OK', y: 2017, yr: '2017', d: 'Test-prep word list arranged as a military campaign. Fortresses of synonyms, moats of antonyms, and daily drills.' },
  { id: 'Z-Z1-03', u: 'Z', s: 'Z1', p: 3, t: 'Six Operas Nobody Stages', a: 'H. Lindqvist', pub: 'Palisade', l: 'EN', ty: 'Music', g: 'Music & opera', st: 'OK', y: 1989, yr: '1989', d: 'Illustrated history of six operas withdrawn after their premieres, with costume plates and the librettos in full.' },
  { id: 'Z-Z1-04', u: 'Z', s: 'Z1', p: 4, t: 'Sword of the Retired Librarian, vol. 1', a: '橋本涼', pub: 'MF文庫J', l: 'JA', ty: 'Light novel', g: 'Light novels', st: 'OK', y: 2021, yr: '2021', d: 'Light novel about a librarian who retires to a village and is immediately asked to fight something in the archives.' },
  { id: 'Z-Z1-05', u: 'Z', s: 'Z1', p: 5, t: 'The Tally', a: 'S. Okonkwo', pub: 'Halfmoon', l: 'EN', ty: 'Fiction', g: 'Literature (English & European)', st: 'OK', y: 2006, yr: '2006', d: 'A shopkeeper keeps count of everything, including the things that count him back.' },
  { id: 'Z-Z1-06', u: 'Z', s: 'Z1', p: 6, t: 'The Unread Shelf', a: 'Bram Tully', pub: 'Ascent', l: 'EN', ty: 'Self-help', g: 'Psychology, self-help & business', st: 'OK', y: 2022, yr: '2022', d: 'Self-help book on the guilt of unread books, which argues, at length, that you should read it.' },
  { id: 'Z-Z2-01', u: 'Z', s: 'Z2', p: 1, t: 'Vagrant Grammar', a: 'M. Ashdown', pub: 'Tolbooth', l: 'EN', ty: 'Linguistics', g: 'Language study & reference', st: 'OK', y: 1985, yr: '1985', d: 'Linguistics monograph on constructions that move between dialects without settling in any. Trees, glosses, and a chapter on nothing.' },
  { id: 'Z-Z2-02', u: 'Z', s: 'Z2', p: 2, t: 'The Vermilion Atlas', a: 'Helene Baptiste', pub: 'Palisade', l: 'EN', ty: 'Art', g: 'Art & visual culture', st: 'OK', y: 1997, yr: '1997', d: 'Art book of maps painted in one pigment, with a long introduction on the trade in cinnabar.' },
  { id: 'Z-Z2-03', u: 'Z', s: 'Z2', p: 3, t: 'Wardens of the Last Aisle', a: 'Kei Morimoto', pub: 'Kodansha', l: 'JA', ty: 'Manga', g: 'Manga & comics', st: 'OK', y: 2018, yr: '2018', d: 'One-shot manga set in a bookshop that closes at midnight and opens somewhere else.' },
  { id: 'Z-Z2-04', u: 'Z', s: 'Z2', p: 4, t: 'Weather for Lawyers', a: 'P. Grange', pub: 'Meridian', l: 'EN', ty: 'Politics', g: 'Politics, law & current affairs', st: 'OK', y: 2013, yr: '2013', d: 'Legal handbook on litigating storms, floods, and acts of God, with case summaries and a glossary of clouds.' },
  { id: 'Z-Z2-05', u: 'Z', s: 'Z2', p: 5, t: '(title hidden by a strip of tape)', a: '', pub: '', l: 'EN', ty: '?', g: 'Unidentified', st: 'Partial', y: null, yr: 'unknown', d: 'Spine covered by tape. Green cloth, gilt rule, roughly octavo. Could be anything.' },
  { id: 'Z-Z2-06', u: 'Z', s: 'Z2', p: 6, t: 'Zero Hour Drills', a: 'L. Brandt', pub: 'Broadstone', l: 'EN', ty: 'Test prep', g: 'Test prep & study guides', st: 'OK', y: 2015, yr: '2015', d: 'Timed practice tests for a licensing exam, printed on paper thin enough to read the next page through.' }
];
