// JavaScript examples for the browser-only playground (from examples/js/).
window.OBF_EXAMPLES = {
  "js": {
    "caesar": "// Caesar cipher: encode a message then decode it back.\nfunction shiftChar(ch, k) {\n  if (ch >= \"a\" && ch <= \"z\") {\n    const base = \"a\".charCodeAt(0);\n    return String.fromCharCode(((ch.charCodeAt(0) - base + k) % 26) + base);\n  }\n  return ch;\n}\n\nfunction encode(message, k) {\n  let out = \"\";\n  for (const c of message) out += shiftChar(c, k);\n  return out;\n}\n\nconst plain = \"the quick brown fox\";\nconst secret = encode(plain, 3);\nconst back = encode(secret, 23);\nconsole.log(\"plain \", plain);\nconsole.log(\"secret\", secret);\nconsole.log(\"back  \", back);\nconsole.log(\"ok\", back === plain);\n",
    "fizzbuzz": "// FizzBuzz for the numbers 1 through 20.\nfunction classify(n) {\n  if (n % 15 === 0) return \"FizzBuzz\";\n  if (n % 3 === 0) return \"Fizz\";\n  if (n % 5 === 0) return \"Buzz\";\n  return String(n);\n}\n\nconst results = [];\nfor (let n = 1; n <= 20; n++) {\n  results.push(classify(n));\n}\nconsole.log(results.join(\" \"));\n",
    "primes": "// Sieve of Eratosthenes: primes below 50.\nfunction primesBelow(limit) {\n  const sieve = new Array(limit).fill(true);\n  sieve[0] = false;\n  if (limit > 1) sieve[1] = false;\n  for (let i = 2; i < limit; i++) {\n    if (sieve[i]) {\n      for (let j = i * i; j < limit; j += i) sieve[j] = false;\n    }\n  }\n  const out = [];\n  for (let i = 0; i < limit; i++) if (sieve[i]) out.push(i);\n  return out;\n}\n\nconst found = primesBelow(50);\nconsole.log(\"count\", found.length);\nconsole.log(\"primes\", found.join(\",\"));\n",
    "wordcount": "// Count word frequencies in a fixed passage and show the top five.\nconst text = \"the quick brown fox jumps over the lazy dog \"\n  + \"the dog was not amused and the fox ran away \"\n  + \"over the hill and far away the fox went\";\n\nfunction countWords(passage) {\n  const counts = {};\n  for (const word of passage.split(\" \")) {\n    counts[word] = (counts[word] || 0) + 1;\n  }\n  return counts;\n}\n\nconst freq = countWords(text);\nconst ranked = Object.keys(freq).sort((a, b) => freq[b] - freq[a] || (a < b ? -1 : 1));\nfor (const word of ranked.slice(0, 5)) {\n  console.log(word, freq[word]);\n}\n"
  }
};
