/* Grammar Fossil Dig: bundled sample texts (public domain, or written for this page).
   Loaded by index.html and reused by the Node self-test, hence the module.exports tail. */
var FOSSIL_PRESETS = [
  {
    id: "beowulf", name: "Beowulf, Prelude (Gummere, 1910)", ref: false,
    text: "Lo, praise of the prowess of people-kings of spear-armed Danes, in days long sped, we have heard, and what honor the athelings won! Oft Scyld the Scefing from squadroned foes, from many a tribe, the mead-bench tore, awing the earls. Since erst he lay friendless, a foundling, fate repaid him: for he waxed under welkin, in wealth he throve, till before him the folk, both far and near, who house by the whale-path, heard his mandate, gave him gifts: a good king he! To him an heir was afterward born, a son in his halls, whom heaven sent to favor the folk, feeling their woe that erst they had lacked an earl for leader so long a while; the Lord endowed him, the Wielder of Wonder, with world's renown. Famed was this Beowulf: far flew the boast of him, son of Scyld, in the Scandian lands. So becomes it a youth to quit him well with his father's friends, by fee and gift, that to aid him, aged, in after days, come warriors willing, should war draw nigh, liegemen loyal: by lauded deeds shall an earl have honor in every clan."
  },
  {
    id: "chaucer", name: "Chaucer, General Prologue (modernised here)", ref: false,
    text: "When April with its sweet showers has pierced the drought of March to the root, and bathed every vein in such liquid by whose power the flower is engendered; when Zephyrus also with his sweet breath has breathed upon the tender shoots in every wood and heath, and the young sun has run half his course in the Ram, and small birds make melody that sleep all night with open eye, so nature pricks them in their hearts; then folk long to go on pilgrimages, and palmers to seek strange shores, to distant shrines known in sundry lands; and especially from every shire's end of England they wend to Canterbury, to seek the holy blissful martyr who helped them when they were sick. It befell that in that season on a day, in Southwark at the Tabard as I lay, ready to go on my pilgrimage to Canterbury with a full devout heart, at night there came into that hostelry well nine and twenty in a company of sundry folk, by chance fallen into fellowship, and pilgrims were they all, that toward Canterbury would ride."
  },
  {
    id: "kjv", name: "Psalm 23 (King James Version, 1611)", ref: "Psalm 23",
    text: "The Lord is my shepherd; I shall not want. He maketh me to lie down in green pastures: he leadeth me beside the still waters. He restoreth my soul: he leadeth me in the paths of righteousness for his name's sake. Yea, though I walk through the valley of the shadow of death, I will fear no evil: for thou art with me; thy rod and thy staff they comfort me. Thou preparest a table before me in the presence of mine enemies: thou anointest my head with oil; my cup runneth over. Surely goodness and mercy shall follow me all the days of my life: and I will dwell in the house of the Lord for ever."
  },
  {
    id: "gibbon", name: "Gibbon, Decline and Fall, ch. 1 (1776)", ref: "Gibbon",
    text: "In the second century of the Christian era, the empire of Rome comprehended the fairest part of the earth, and the most civilized portion of mankind. The frontiers of that extensive monarchy were guarded by ancient renown and disciplined valour. The gentle but powerful influence of laws and manners had gradually cemented the union of the provinces. Their peaceful inhabitants enjoyed and abused the advantages of wealth and luxury. The image of a free constitution was preserved with decent reverence: the Roman senate appeared to possess the sovereign authority, and devolved on the emperors all the executive powers of government. During a happy period of more than fourscore years, the public administration was conducted by the virtue and abilities of Nerva, Trajan, Hadrian, and the two Antonines. It is the design of this, and of the two succeeding chapters, to describe the prosperous condition of their empire; and afterwards, from the death of Marcus Antoninus, to deduce the most important circumstances of its decline and fall; a revolution which will ever be remembered, and is still felt by the nations of the earth."
  },
  {
    id: "lincoln", name: "Lincoln, Gettysburg Address (1863)", ref: false,
    text: "Four score and seven years ago our fathers brought forth on this continent, a new nation, conceived in Liberty, and dedicated to the proposition that all men are created equal. Now we are engaged in a great civil war, testing whether that nation, or any nation so conceived and so dedicated, can long endure. We are met on a great battle-field of that war. We have come to dedicate a portion of that field, as a final resting place for those who here gave their lives that that nation might live. It is altogether fitting and proper that we should do this. But, in a larger sense, we can not dedicate, we can not consecrate, we can not hallow this ground. The brave men, living and dead, who struggled here, have consecrated it, far above our poor power to add or detract. The world will little note, nor long remember what we say here, but it can never forget what they did here. It is for us the living, rather, to be dedicated here to the unfinished work which they who fought here have thus far so nobly advanced. It is rather for us to be here dedicated to the great task remaining before us, that from these honored dead we take increased devotion to that cause for which they gave the last full measure of devotion; that we here highly resolve that these dead shall not have died in vain; that this nation, under God, shall have a new birth of freedom; and that government of the people, by the people, for the people, shall not perish from the earth."
  },
  {
    id: "darwin", name: "Darwin, Origin of Species, last paragraph (1859)", ref: false,
    text: "It is interesting to contemplate an entangled bank, clothed with many plants of many kinds, with birds singing on the bushes, with various insects flitting about, and with worms crawling through the damp earth, and to reflect that these elaborately constructed forms, so different from each other, and dependent on each other in so complex a manner, have all been produced by laws acting around us. These laws, taken in the largest sense, being Growth with Reproduction; Inheritance which is almost implied by reproduction; Variability from the indirect and direct action of the external conditions of life, and from use and disuse; a Ratio of Increase so high as to lead to a Struggle for Life, and as a consequence to Natural Selection, entailing Divergence of Character and the Extinction of less-improved forms. Thus, from the war of nature, from famine and death, the most exalted object which we are capable of conceiving, namely, the production of the higher animals, directly follows. There is grandeur in this view of life, with its several powers, having been originally breathed into a few forms or into one; and that, whilst this planet has gone cycling on according to the fixed law of gravity, from so simple a beginning endless forms most beautiful and most wonderful have been, and are being, evolved."
  },
  {
    id: "abstract", name: "A modern paper abstract (invented)", ref: "Paper abstract",
    text: "We introduce a scalable framework for contrastive representation learning in multimodal transformer architectures. Our approach leverages hierarchical tokenization and adaptive normalization to optimize cross-domain generalization under limited supervision. Extensive experiments on standard benchmarks demonstrate consistent improvements in accuracy, robustness, and computational efficiency relative to prior baselines. We further analyze the emergent structure of the learned embeddings and discuss implications for interpretability, calibration, and downstream deployment. Code and pretrained checkpoints are publicly available."
  }
];
if (typeof module !== "undefined") module.exports = FOSSIL_PRESETS;
